server:
  port: 8200

spring:
  application:
    name: pedidos-service

  datasource:
    url: jdbc:h2:mem:pedidosdb
    driver-class-name: org.h2.Driver
    username: admin
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
      prefer-ip-address: true
